spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.hibernate.show-sql=true
    spring.datasource.url=jjdbc:postgresql://ec2-54-157-79-121.compute-1.amazonaws.com:5432/d7sjmov2mie7jl
    spring.datasource.username=rognbyedeqgdcp
    spring.datasource.password=27fb5d41ffb386fbb2b3f73f4486760e6dd30a14bd2f85cb183aefffe6014efc

